version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - cd deployment
      - ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - env
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh --template-bucket ${TEMPLATE_OUTPUT_BUCKET} --code-bucket ${DIST_OUTPUT_BUCKET} --version ${VERSION} --region ${AWS_REGION} --solution-name ${SOLUTION_NAME}  --use_solution_builder_pipeline
      - echo "Build completed `date`"
      - echo "Starting open-source-dist `date` in `pwd`"
      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
      - echo "Open Source Dist completed `date`"
  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"
artifacts:
  files:
    - .gitignore
    - buildspec.yml
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.txt
    - NOTICE.txt
    - README.md
    - sonar-project.properties
    - THIRD_PARTY_LICENSES.txt
    - deployment/**/*
    - source/**/*
    - .github/**/*
